# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: David Proctor dot io
email: david@davidproctor.io
description: > # this means to ignore newlines until "baseurl:"
  David Proctor: Programmer. Artist. Legend. I'm a software developer with extensive experience in Go, C#, C++, Java, and Python.
  This site collects my personal projects and work that I produce as a hobby.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.davidproctor.io" # the base hostname & protocol for your site
github_username:  david-proctor
bitbucket_username: DavidProctor
linkedin_username: david-proctor

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-srcset
exclude:
  - Gemfile
  - Gemfile.lock

# sass settings
sass:
  sass_dir: _sass

# dark code theme is 'native' from https://github.com/jwarby/jekyll-pygments-themes
